version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    ignore:
      # These are peer deps of Cargo and should not be automatically bumped
      - dependency-name: 'semver'
      - dependency-name: 'crates-io'
    reviewers:
      - jewlexx
    assignees:
      - jewlexx
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - jewlexx
    assignees:
      - jewlexx
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
